Задания с типами данных
tanyatroyanova/testing pull request #4
Opened 2020-01-19 12:19 UTC by tanyatroyanova

2020-01-21 13:44 UTC, Ventura27 requested changes

2020-01-21 13:44 UTC, Ventura27 commented on types.js
> +alert( `hello ${name}` ); // hello Ilya
Лишние пробелы перед и после строк

2020-01-21 13:44 UTC, Ventura27 commented on types.js
> +"" + 1 + 0 //"10"
Один раз тут отпишу, старайся в комментах после // оставлять один пробел  и затем сам коммент, так более читабильно

2020-01-21 13:44 UTC, Ventura27 commented on types.js
> +" \t \n" - 2 //-2
Нужная пустая строка в конце файла

2020-01-21 13:44 UTC, Ventura27 commented on types.js
> +"  -9  " - 5 // -14
лишние пробелы перед и после -9

2020-01-21 19:08 UTC, tanyatroyanova commented on types.js
> +"  -9  " - 5 // -14
здесь пробелы были в самом задании
если их удалить - изменится результат в первом случае

2020-01-22 06:41 UTC, Ventura27 commented on types.js
> +"  -9  " - 5 // -14
ок

2020-01-22 07:08 UTC, Ventura27 approved these changes

2020-01-22 07:44 UTC, merged