Задания с логическими операторами
tanyatroyanova/testing pull request #6
Opened 2020-01-19 14:58 UTC by tanyatroyanova

2020-01-21 14:01 UTC, Ventura27 requested changes

2020-01-21 14:01 UTC, Ventura27 commented on logical_operators.js
> +alert( null || 2 || undefined ); // 2 - первое истинное значение
лишние пробелы перед null и после undefined

2020-01-21 14:01 UTC, Ventura27 commented on logical_operators.js
> +alert( alert(1) || 2 || alert(3) ); // 1 (т.к. alert выполнится), 2 - первое истинное
лишние пробелы перед alert(1) и после alert(3)

2020-01-21 14:01 UTC, Ventura27 commented on logical_operators.js
> +alert( 1 && null && 2 );//  null - первое ложное значение
лишние пробелы перед 1 и после 2
перед // не хватает пробела

2020-01-21 14:01 UTC, Ventura27 commented on logical_operators.js
> +alert( alert(1) && alert(2) ); // 1 - первое ложное,alert(1) возвращает undefined -> выполнится еще alert(undefined)
лишние пробелы перед alert(1) и после alert(2)

2020-01-21 14:01 UTC, Ventura27 commented on logical_operators.js
> +alert( alert(1) && alert(2) ); // 1 - первое ложное,alert(1) возвращает undefined -> выполнится еще alert(undefined)
![image](https://user-images.githubusercontent.com/36276658/72810113-fb185880-3c6d-11ea-91e9-82822c4ff926.png)
почему alert(1) возвращает undefined?

2020-01-21 14:01 UTC, Ventura27 commented on logical_operators.js
> +alert( null || 2 && 3 || 4 ); //3 ;  сначала выполниться 2 && 3, которое вернет 3 т.к. оба значения истинны; после выполниться alert(3)
лишние пробелы перед null и после 4

2020-01-21 14:01 UTC, Ventura27 commented on logical_operators.js
> +if(age < 14 || age > 90 );
нужен пробел после if
удалить пробел после 90

2020-01-21 14:01 UTC, Ventura27 commented on logical_operators.js
> +if ( !(age >= 14) && !(age <= 90) );
удали пробелы перед !(age и после 90)

2020-01-21 14:01 UTC, Ventura27 commented on logical_operators.js
> +if (-1 || 0) alert( 'first' ); // выполниться; результат (-1 || 0)=-1 т.е истина
удалить пробелы перед и после 'first'

2020-01-21 14:01 UTC, Ventura27 commented on logical_operators.js
> +if (-1 && 0) alert( 'second' ); //не выполниться; результат (-1 && 0)=0 т.е ложь
удалить пробелы перед и после 'second'

2020-01-21 14:01 UTC, Ventura27 commented on logical_operators.js
> +if (null || -1 && 1) alert( 'third' ); //выполниться; сначала выполниться (-1 && 1)=1;затем (null || 1) = 1; результат в if(1) т.е истина
удалить пробелы перед и после 'third'

2020-01-21 14:01 UTC, Ventura27 commented on logical_operators.js
> +}
Оставляй пустую строку в конце файла

2020-01-21 14:01 UTC, Ventura27 commented on logical_operators.js
> +let login = prompt('Введите логин: ','');
пробел перед вторым аргументом

2020-01-21 14:01 UTC, Ventura27 commented on logical_operators.js
> +if ( login == 'Админ'){
){ - пробел
перед login пробел

2020-01-21 14:01 UTC, Ventura27 commented on logical_operators.js
> +    password = prompt('Введите пароль','');
пробел перед вторым аргументом

2020-01-21 14:01 UTC, Ventura27 commented on logical_operators.js
> +}else if(login == '' || login == null){
пробелы перед и после else if
){ - пробел между

2020-01-21 14:01 UTC, Ventura27 commented on logical_operators.js
> +}else {
пробел перед else

2020-01-21 14:01 UTC, Ventura27 commented on logical_operators.js
> +if (password == '' || password == null){
){ - пробел

2020-01-21 14:01 UTC, Ventura27 commented on logical_operators.js
> +}else if (password == 'Я главный'){
пробел перед else
){ - пробел

2020-01-21 14:01 UTC, Ventura27 commented on logical_operators.js
> +}else {
пробел перед else

2020-01-21 19:38 UTC, tanyatroyanova commented on logical_operators.js
> +alert( alert(1) && alert(2) ); // 1 - первое ложное,alert(1) возвращает undefined -> выполнится еще alert(undefined)
если alert() используется в качестве параметра внутри другого alert, то этот alert выведет undefined
в данном примере выполнился сначала alert(1), который вывел 1, а после выполнился:
alert(alert(1)) - который возвращает undefined

2020-01-22 07:09 UTC, Ventura27 commented on logical_operators.js
> +alert( alert(1) && alert(2) ); // 1 - первое ложное,alert(1) возвращает undefined -> выполнится еще alert(undefined)
хорошо)

2020-01-22 07:10 UTC, Ventura27 approved these changes

2020-01-22 07:32 UTC, merged