Задания по теме Функции
tanyatroyanova/testing pull request #9
Opened 2020-01-19 21:46 UTC by tanyatroyanova

2020-01-21 14:23 UTC, Ventura27 requested changes

2020-01-21 14:23 UTC, Ventura27 commented on function.js
> +    (age > 18)
зачем эта строка?

2020-01-21 14:23 UTC, Ventura27 commented on function.js
> +function min(a,b) {
пробел между аргументами

2020-01-21 14:23 UTC, Ventura27 commented on function.js
> +  if (confirm(question)) yes()
если confirm функция, то пробелы как раз можно оставить перед и после, то есть так:
if ( confirm(question) )

2020-01-21 14:23 UTC, Ventura27 commented on function.js
> +}
поправь стиль с учетом предыдущих комментов

2020-01-21 14:23 UTC, Ventura27 commented on function.js
> +}
поправь стиль с учетом предыдущих комментов

2020-01-21 14:23 UTC, Ventura27 commented on function.js
> +  if (confirm(question)) yes()
если юзаешь if старайся использовать классическую запись с {}, так более читаемо

2020-01-21 14:23 UTC, Ventura27 commented on function.js
> +ask("Вы согласны?",yes,no);
пробелы между аргументами

2020-01-21 14:23 UTC, Ventura27 commented on function.js
> +
лишние две пустые строки

2020-01-21 20:04 UTC, tanyatroyanova commented on function.js
> +  if (confirm(question)) yes()
это код с задания
я его не закомментила

2020-01-22 07:14 UTC, Ventura27 commented on function.js
> +    (age > 18)
не ответила

2020-01-22 07:14 UTC, Ventura27 commented on function.js
> +  if (confirm(question)) yes()
окай

2020-01-22 07:16 UTC, Ventura27 commented on function.js
> +function checkAge(age) {
Ответь плиз для чего строка с (age > 18)

2020-01-22 07:21 UTC, tanyatroyanova commented on function.js
> +    (age > 18)
удалила
она не нужна

2020-01-22 07:21 UTC, tanyatroyanova commented on function.js
> +function checkAge(age) {
не нужна

2020-01-22 07:24 UTC, Ventura27 approved these changes

2020-01-22 07:25 UTC, merged